services:
  data-compare-api-service:
    build:
      context: ./
      dockerfile: ./DataCompareAPIs/Dockerfile
    ports:
      - "8085:8085"  # Port mapping for the API service
    container_name: data-compare-api-service
    depends_on:
      - di-keycloak
      - kafka
      - minio
    environment:
      NBS_DBPASSWORD: ${DB_PASSWORD}
      NBS_DBSERVER: ${DB_SERVER}
      NBS_DBUSER: ${DB_USER}
      NND_AUTH_URI: http://localhost:8080/realms/NBS
      DC_AUTH_URI:  http://localhost:8100/realms/NBS
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      AWS_KEY_ID: localrootuser
      AWS_ACCESS_KEY: localpass
      S3_BUCKET_NAME: local-bucket
      S3_ENDPOINT: http://minio:9000
      S3_PATH_STYLE: "true"
      AWS_IAM: "false"
    networks:
      - datacompare

  data-compare-processor-service:
    build:
      context: ./
      dockerfile: ./DataCompareProcessor/Dockerfile
    ports:
      - "8086:8086"
    container_name: data-compare-processor-service
    depends_on:
      - di-keycloak
      - kafka
      - minio
    environment:
      NBS_DBPASSWORD: ${DB_PASSWORD}
      NBS_DBSERVER: ${DB_SERVER}
      NBS_DBUSER: ${DB_USER}
      NND_AUTH_URI: http://localhost:8080/realms/NBS
      DC_AUTH_URI: http://localhost:8100/realms/NBS
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      AWS_KEY_ID: localrootuser
      AWS_ACCESS_KEY: localpass
      S3_BUCKET_NAME: local-bucket
      S3_ENDPOINT: http://minio:9000
      S3_PATH_STYLE: "true"
      AWS_IAM: "false"
    networks:
      - datacompare

  di-keycloak:
    container_name: di-keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8100:8080"
    volumes:
      - ./imports:/opt/keycloak/data/import
    env_file:
      - dataingestion.env
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm"
    networks:
      - datacompare

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: rtr-zookeeper
    container_name: rtr-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - datacompare

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://kafka:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    networks:
      - datacompare

  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z # Use a specific release tag
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: localrootuser
      MINIO_ROOT_PASSWORD: localpass
    command: ["server", "--console-address", ":9001", "/data"]
    restart: unless-stopped
    networks:
      - datacompare

volumes:
  minio_data:
    driver: local

networks:
  datacompare:
    name: datacompare
